### PR TITLE
DEV-16184-minio-ingress.tpl-port-fix

### PR DESCRIPTION
**Pull request by dilerous**
Reference to the minio svc port was incorrect. The minio svc is listening on port 80 not the spec port defined 9000.

### CODE REVIEW

**Comment by dilerous** [comment]
Added TLS section for all ingress templates. To track the DEV ticket in JIRA is https://cnvrgio.atlassian.net/browse/DEV-16208

**Comment by itaynvn** [comment]
**tickets:**
https://cnvrgio.atlassian.net/browse/DEV-16184
https://cnvrgio.atlassian.net/browse/DEV-16208

**Review by Dimss — APPROVED** [review]
@TomerHasson @dilerous looks good by me. 
Sill need to run the automation to make sure there is no regression issues.

**Comment by itaynvn** [comment]
this PR was merged to this branch: https://github.com/AccessibleAI/cnvrg-operator/pull/129

**Pull request closed without merging**
